// Generated by Isabelle-LLVM. Do not modify.
#ifndef _INTROSORT_H
#define _INTROSORT_H 1


typedef struct {
  char*data;
  struct {
    int64_t size;
    int64_t capacity;
  };
} llstring;

char llstrcmp(llstring*, llstring*);
void str_init(llstring*);
void str_append(llstring*, char);
uint64_t* introsort(uint64_t*, int64_t, int64_t);
llstring* str_introsort(llstring*, int64_t, int64_t);

#endif
